# Generated by Django 5.2.4 on 2025-09-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="created_at",
            new_name="created",
        ),
    ]
