# Generated by Django 5.2.4 on 2025-09-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teacher_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ["-created"],
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
            },
        ),
    ]
