# Generated by Django 5.2.4 on 2025-08-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="created_at",
            new_name="created",
        ),
    ]
