# Generated by Django 5.2.4 on 2025-09-01 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_rename_created_at_course_created"),
        ("teacher", "0003_alter_teacher_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["title"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the course was created"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(help_text="Detailed description of the course"),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(help_text="Title of the course", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="tutor",
            field=models.ForeignKey(
                help_text="The teacher who created this course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="teacher.teacher",
            ),
        ),
    ]
