# Generated by Django 5.2.4 on 2025-09-01 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_options_alter_course_created_and_more"),
        ("student", "0002_student_created"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(help_text="Age of the student."),
        ),
        migrations.AlterField(
            model_name="student",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Profile creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrolled_courses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Courses the student is enrolled in.",
                related_name="students",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_name",
            field=models.CharField(
                help_text="Father's name of the student.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.CharField(
                blank=True,
                help_text="Class/grade of the student, e.g., '10th Grade'.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_name",
            field=models.CharField(
                help_text="Full name of the student.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                help_text="Linked user account with role='student'.",
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
