# Generated by Django 5.2.4 on 2025-09-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_price"),
        ("student", "0003_alter_student_age_alter_student_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrolled_courses",
            field=models.ManyToManyField(
                help_text="Courses the student is enrolled in.",
                related_name="students",
                to="courses.course",
            ),
        ),
    ]
